### ISSUE TITLE
Recommended gem for N+1 detection: bullet

### ISSUE THREAD

**Issue by fengb** [jmmastey/level_up#107]
Almost feels like cheating: https://github.com/flyerhzm/bullet

Automatically detects N+1 problems. It's not perfect, and I've gotten a few false positives, but it really helped nip things in the bud.

It's also extremely annoying to add to an existing app so it might be interesting to have an entire exercise to shut it up.

**Comment by jmmastey** [comment]
Neat. Did you try it on this codebase at all? If it works decently, we could add a resource to `performance.html.haml` with it?
