### ISSUE TITLE
Ruby Style Guide

### ISSUE THREAD

**Issue by paulghaddad** [jmmastey/level_up#110]
Hey Joe,

What are your thoughts about the Github style guide: https://github.com/styleguide/ruby

I was thinking of submitting a pull request for Level 2. I think it is a great guide as it gives good examples. While I am not in complete agreement about everything, such as the Hash syntax, it does cover some key points:
* Exception handling
* The `||=` operator
* Keyword arguments

I think it is pretty concise, contains very practical information and is pretty much on the money. I'll also toss this to @djkotowski  for his thoughts. 

If you like it, I'll submit a PR.

Paul

**Comment by jmmastey** [comment]
Generally I like it. There are a few points that I don't personally use, but it's clearly superior to not having a style. My only concern, and it's not a small one, is getting hound to follow these rules. If that is covered, I'll merge (assuming @djkotowski agrees).

**Comment by jmmastey** [comment]
Hey @paulghaddad any word from @djkotowski? Also, any luck on seeing where this falls relative to hound.yml?

**Comment by paulghaddad** [comment]
Hey @jmmastey let me talk to Dan now. If he agrees, I'll submit a PR for `.hound.yml`, if it is feasible.

**Comment by jmmastey** [comment]
Closing for now, because I don't think this'll be moved forward :)
