### ISSUE TITLE
"you've been enrolled!" email links out to walled page

### ISSUE THREAD

**Issue by KaraAJC** [jmmastey/level_up#125]
My email links to courses/7, which returns an error page, instead of a redirect, or a page to indicate I am not logged in. 
![screen shot 2015-10-06 at 12 36 59 pm](https://cloud.githubusercontent.com/assets/7103652/10316927/6aa138be-6c27-11e5-8610-83f4a72eddb8.png)

**Comment by jmmastey** [comment]
Hey Kara, thanks for opening this. It's not technically walled, but it looks like the code that was checking your completion percentage fails when you're a guest. I've got an updated branch incoming soon (https://github.com/jmmastey/level_up/tree/anonymous_course_view).

I'd really love to redirect directly to one of the content page (for categories, as opposed to the course), but that seems inelegant here. Thanks!

**Comment by KaraAJC** [comment]
I would think as a baseline, it would redirect you to login so you could continue to the courses page to continue your work... Thanks for responding so quickly! I'm looking through the branch, I'd love to see the changes you made, did that guest class exist before I raised this issue?

**Comment by jmmastey** [comment]
Yeah, it existed and I'm mostly happy with it. I started that idea after talking to Sandi Metz a bunch and wanting to try out the concept of Polymorphism Over Conditionals.

The trick is that -- as you can see -- the `User` class is clearly already a bit overburdened. I don't usually think of AR associations as being "responsibilities", but the guest class has had to replicate a bunch of stuff to keep up.

More than one bug has cropped up where the User and Guest classes fall out of sync. I wish there was a better implementation of the `NullObject` pattern for ActiveRecord.

**Comment by jmmastey** [comment]
On the redirect: we could do that, and if there's no course found (or if it belongs to an organization of which you're not a part) we do at least redirect to the courses page. I think mostly people get to this page because they intend to view a specific course, though, so I think showing them 0% completion is maybe more accurate than bouncing them out entirely.

Honestly, this page is almost an afterthought (I think most people don't visit it much), but clearly it's still creating little headaches :)

**Comment by jmmastey** [comment]
Oh, and on login redirects: I'd bet a dollar that login doesn't correctly redirect back to the page that bounced you, sadly... I'd love to see a branch that fixes it, but the usage mode for most learners hasn't made it into a big issue for me.

**Comment by jmmastey** [comment]
Cool, merged, should be fixed now.
